Algoritmo "exercicio_tempo_de_jogo"

Var
   horaInicial, horaFinal, duracao : inteiro
Inicio
      escreva("Hora inicial: ")
      leia(horaInicial)
      escreva("Hora final: ")
      leia(horaFinal)
      
      se horaFinal > horaInicial entao
         duracao <- horaFinal - horaInicial
      senao
         duracao <- 24 - horaInicial + horaFinal
      fimse
      
      escreval("O JOGO DUROU ", duracao, " HORA(S)")
Fimalgoritmo